### ISSUE TITLE
errand-config: does not process pre-delete errands

### ISSUE THREAD

**Issue by caresourceplatform** [rahul-kj/tile-config-convertor#1]
We have tiles that have pre-delete errands and this will not output errands that are pre-delete.

Not the end of the world as we can work around it.
All you have to do is pull the errands for the staged tile and then add the pre-delete errand(s) to the params.yml and in the apply config area add: 
run_pre_delete:
  \<task-name\>: true|false|default

This is a freaking awesome tool!

Thanks!

**Comment by rahulkj** [comment]
@caresourceplatform - yeah its a easy one to add. I will add this this week. Thanks for your gracious comment :)

**Comment by rahulkj** [comment]
@caresourceplatform - on your next execution of the pipeline, the changes will reflect.

Added the missing errands with their `pre_delete` status
